mkdir build
mkdir result
mkdir result/attribution
mkdir result/laptop
mkdir result/plot_performance
mkdir result/rank
mkdir result/single_query_performance
mkdir result/vis_performance
mkdir index
mkdir index/memory_index
mkdir index/qrs_to_sample_index
mkdir index/query_distribution
